import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { homedir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const target = join(process.env.XDG_CONFIG_HOME || join(homedir(), '.config'), 'opencode', 'plugins', 'zellij-namer');
for (const name of ['index', 'tui']) {
  if (!existsSync(join(root, 'dist', `${name}.js`))) throw new Error('Run bun run build first.');
  const file = join(target, `${name}.ts`);
  if (existsSync(file) && !readFileSync(file, 'utf8').includes('/opencode-zellij-namer/dist/')) {
    throw new Error(`Existing plugin at ${file}; move it aside before installing.`);
  }
}
mkdirSync(target, { recursive: true });
for (const name of ['index', 'tui']) {
  writeFileSync(join(target, `${name}.ts`), `// Gemini Zellij Namer V2 — generated by scripts/install.ts\nexport { default } from ${JSON.stringify(join(root, 'dist', `${name}.js`))};\n`);
}
console.log(`Installed V2 entrypoints in ${target}. Keep this checkout in place.`);
